# Generated by PackScript 0.1.2
$say packscript> $(message) < actual working macro parameter
say packscript> $(message) < that is just text
say packscript> 2 + 2 = 4 < this works because it is compile time
